var GAME_LEVELS = [
  ["              x                                                                 ",
   "              x                                                                 ",  
   "              x                                                                 ",
   "              x                                                        o        ",
   "              x                                                                 ",
   "   @          x                   xxxxx    xxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxx",
   "xxxxxxxx   =  x                                    x          x!!!!x             ",
   "       x      xxxxxxxxxxxxxxxxx                    x          xxxxxx            ",
   "   o   x                      x                    x                            ",
   "   =   x                      x                    x                             ",
   "       x            xxxx      x x                  x                             ",
   "       x      x   =    x      x                    x                             ",
   "       xxxxxxxxxxxxxxxxxxx   =xxxx    x            x                             ",
   "      xx!!!x                     x!!!!x            x                             ",
   "       xxvxx                =    xxxxxx       =    x                             ",
   "                                 x       xxxx      x                             ",
   "                        xxxxxxxxxx      v          x                             ",
   "!!xx                   x                       xx  x                             ",
   "!!x                   x                            x                             ",
   "!!x    x         =    x                   xxx      x                             ",
   "!!x          xxxx                                  x                             ",
   "!!x          x  x                                  x                            ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxx                            ",
   "                              x!!!x                                             ",
   "                              x!!!x                                             ",
   "                              xxxxx                                             ",],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                       x                                           ",
   "                                                                       x                                           ",
   "                                                              o        x                                           ",
   "                                                                       x                                           ",
   "                                                         xxxxxx    =   x                                            ",
   "                                            xxxxxxxxxxxxxx             x                                            ",
   "                                           ox                |         x                                             ",
   "                                            x                          x                                             ",
   "                        o                  xx                          x                                             ",
   "         x                                  x     =     xxxxxxxxxxxxxxxx                                             ",
   "         x              xxxxxxxxxxxx     o  x                          x                                             ",
   "         x              x!x                 x                          x                                             ",
   "         x               v              xxxxx          o               x                                            ",
   "         x                                  x                          x                                            ",
   "         x                                  xxxxxxxxxxxxxxxx           x                                                  ",
   "         x                      o     xxxxxxx              x       o   x                                              ",
   "         x     @             xxxxxxxxxxx                   x           x                                             ",
   "         xxxxxxxxxxxxxxxxxxxxx                             xxxxxxxxxxxxx                                           ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                               o                                               ",
   "                                                                                        x    o                  ",
   "                                                               x     x     x     x                            ",
   "                                                                                             x                 ",
   "                                                    x                                                          ",
   "                                                    x      !!!!!!!!!!!!!!!!!!!!!!       x                       ",
   "                                                    x                                                          ",
   "                                                    x                             x                             ",
   "                                                    x                                                         ",
   "                                           xx       x   x      x                                                ",
   "                                      xxxxxxxxx    xxxxxxxx                            x                      ",
   "                                      x   x x=     x   x                                                        ",
   "                                      x   x x=     x   x                      xxxxx                                  ",
   "                                     xx   x x=     x   x                                                       ",
   "                                      x   x x=     x   x            xxx                                        ",
   "                                      x   x x=     x   x           x!!!xxx                                       ",
   "                                      x   x x=     x   x     o      xxx       xxx                              ",
   "                                     xx   x x=     x   x         x           x!!!xxx                           ",
   "                              o   o   x   x x=     x   x     x                xxv        xxx                   ",
   "                                      x   x x=     x   x              x                 x!!!xxxx     x          ",
   "                             xxx xxx xxx xx x=     x   x!!!v!!!!!!v!!!x                   vx         x          ",
   "                         xxxxx            x x=     x   xv            v                               x                ",
   "                         x                x x=     x   x                                           xxx               ",
   "                 x   =    x               x x=     x   x                                         xxxx                 ",
   "  xxx  =         xxxxxxxxxx               x            o                            o         xxxx                  ",
   "  x x  =         x                        x                                                   x                ",
   "  x    =         x                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                                      ",
   "  x    =        x                                                                                         ",
   "  x    =        x                                                                                         ",
   "  x    =        x                                                                                               ",
   "  x    =       x                                                             ",
   "  x    =       x                                           ",
   "  x    =       x                                      ",
   "  x    =      x                                        ",
   "  x    =  @   x                                                ",
   "  xxxxxxxxxxxxx                                           ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "          @                      w                                                                            ",                     
   "          x   x xxxx x  x     x     x xxxxx xx    x                                                           ",
   "           x x  x  x x  x     x     x   x   x x   x                                                           ",
   "            x   x  x x  x     x  x  x   x   x  x  x                                                           ",
   "            x   x  x x  x     x x x x   x   x   x x                                                           ",
   "            x   xxxx xxxx      x   x  xxxxx x    xx                                                           ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
